project:
  type: website
  output-dir: _site
  title: Showcase Curriculum for Research Software Engineering
  render:
    - "*.qmd"


website:
  title: "RSE Curriculum"
  description: ""
  navbar:
    right:
      - text: "Curriculum"
        href: generation/generated/curriculum.qmd
      - text: "Home"
        href: index.qmd
      - text: "Job Roles"
        href: general/job_roles.qmd
      - text: "Preambel"
        href: general/preambel_general.qmd
      - text: "PDF-Version"
        href: _doc/RSE-Curriculum.pdf


format:
  html:
    theme: lux
    bibliography: references.bib

