project:
  type: website
  output-dir: _site
  title: Showcase Curriculum for Research Software Engineering


website:
  title: "Julian Dehne"
  description: "Julian's Academic Website"
  navbar:
    right:
      - text: "Curriculum"
        href: generation/generated/curriculum.qmd
      - text: "Home"
        href: index.qmd
      - text: "Job Roles"
        href: general/job_roles.qmd
      - text: "Preambel"
        href: general/preambel_general.qmd

format:
  html:
    theme: lux

author:
  - name: Julian Dehne
    orcid: 0000-0001-9265-9619
    url: https://www.researchgate.net/profile/Julian-Dehne
    email: julian.dehne@gesis.org
    twitter: "@DehneJulian"
    affiliations:
      - name: GESIS,  Leibniz-Institut für Sozialwissenschaften
        address: B4-5, 68159 Mannheim
      - name: University of Göttingen
        address: Goßlerstraße 19, 37073 Göttingen

profile:
  default: website
