project:
  type: website
  output-dir: _site
  title: Showcase Curriculum for Research Software Engineering
  render:
    - "*.qmd"


website:
  title: "RSE Curriculum"
  description: ""
  navbar:
    right:
      - text: "Curriculum"
        href: generation/generated/curriculum.qmd
      - text: "Home"
        href: index.qmd
      - text: "Job Roles"
        href: general/job_roles.qmd
      - text: "Preambel"
        href: general/preambel_general.qmd

format:
  html:
    theme: lux
    bibliography: references.bib
  pdf:
    bibliography: references.bib


author:
  - name: Julian Dehne
    orcid: 0000-0001-9265-9619
    url: https://www.researchgate.net/profile/Julian-Dehne
    email: julian.dehne@gesis.org
    twitter: "@DehneJulian"
    affiliations:
      - name: Gesellschaft für Informatik
        address: Rosa-Luxemburg Platz Berlin
      - name: deRSE

profile:
  default: website

