sources:
  - curriculum:
    - name: Computing Curricula 2020
      link: https://dl.acm.org/doi/book/10.1145/3467967
  - courses:
    - name: UP Grundlagen der Programmierung
      link: ""
    - name: UP Praxis der Programmierung
      link: ""
  - programs:
    - name: UP Computational Science Master
    - link: ""
